# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "mobilerx" do
pod 'Firebase', '>= 1.1.12'
end

target "mobilerxTests" do
pod 'Firebase', '>= 1.1.12'
end

